# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aysat/RadarDatabase

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aysat/RadarDatabase

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aysat/RadarDatabase/CMakeFiles /home/aysat/RadarDatabase//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aysat/RadarDatabase/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named appRadarDatabase

# Build rule for target.
appRadarDatabase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase
.PHONY : appRadarDatabase

# fast build rule for target.
appRadarDatabase/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/build
.PHONY : appRadarDatabase/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_qmltyperegistration

# Build rule for target.
appRadarDatabase_qmltyperegistration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_qmltyperegistration
.PHONY : appRadarDatabase_qmltyperegistration

# fast build rule for target.
appRadarDatabase_qmltyperegistration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_qmltyperegistration.dir/build.make CMakeFiles/appRadarDatabase_qmltyperegistration.dir/build
.PHONY : appRadarDatabase_qmltyperegistration/fast

#=============================================================================
# Target rules for targets named all_qmltyperegistrations

# Build rule for target.
all_qmltyperegistrations: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmltyperegistrations
.PHONY : all_qmltyperegistrations

# fast build rule for target.
all_qmltyperegistrations/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_qmltyperegistrations.dir/build.make CMakeFiles/all_qmltyperegistrations.dir/build
.PHONY : all_qmltyperegistrations/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_qmllint

# Build rule for target.
appRadarDatabase_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_qmllint
.PHONY : appRadarDatabase_qmllint

# fast build rule for target.
appRadarDatabase_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_qmllint.dir/build.make CMakeFiles/appRadarDatabase_qmllint.dir/build
.PHONY : appRadarDatabase_qmllint/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_qmllint_json

# Build rule for target.
appRadarDatabase_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_qmllint_json
.PHONY : appRadarDatabase_qmllint_json

# fast build rule for target.
appRadarDatabase_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_qmllint_json.dir/build.make CMakeFiles/appRadarDatabase_qmllint_json.dir/build
.PHONY : appRadarDatabase_qmllint_json/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_qmllint_module

# Build rule for target.
appRadarDatabase_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_qmllint_module
.PHONY : appRadarDatabase_qmllint_module

# fast build rule for target.
appRadarDatabase_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_qmllint_module.dir/build.make CMakeFiles/appRadarDatabase_qmllint_module.dir/build
.PHONY : appRadarDatabase_qmllint_module/fast

#=============================================================================
# Target rules for targets named all_qmllint

# Build rule for target.
all_qmllint: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint
.PHONY : all_qmllint

# fast build rule for target.
all_qmllint/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_qmllint.dir/build.make CMakeFiles/all_qmllint.dir/build
.PHONY : all_qmllint/fast

#=============================================================================
# Target rules for targets named all_qmllint_json

# Build rule for target.
all_qmllint_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_json
.PHONY : all_qmllint_json

# fast build rule for target.
all_qmllint_json/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_qmllint_json.dir/build.make CMakeFiles/all_qmllint_json.dir/build
.PHONY : all_qmllint_json/fast

#=============================================================================
# Target rules for targets named all_qmllint_module

# Build rule for target.
all_qmllint_module: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_qmllint_module
.PHONY : all_qmllint_module

# fast build rule for target.
all_qmllint_module/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_qmllint_module.dir/build.make CMakeFiles/all_qmllint_module.dir/build
.PHONY : all_qmllint_module/fast

#=============================================================================
# Target rules for targets named dump_qml_context_properties

# Build rule for target.
dump_qml_context_properties: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dump_qml_context_properties
.PHONY : dump_qml_context_properties

# fast build rule for target.
dump_qml_context_properties/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dump_qml_context_properties.dir/build.make CMakeFiles/dump_qml_context_properties.dir/build
.PHONY : dump_qml_context_properties/fast

#=============================================================================
# Target rules for targets named clean_qml_context_properties

# Build rule for target.
clean_qml_context_properties: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_qml_context_properties
.PHONY : clean_qml_context_properties

# fast build rule for target.
clean_qml_context_properties/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_qml_context_properties.dir/build.make CMakeFiles/clean_qml_context_properties.dir/build
.PHONY : clean_qml_context_properties/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_copy_qml

# Build rule for target.
appRadarDatabase_copy_qml: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_copy_qml
.PHONY : appRadarDatabase_copy_qml

# fast build rule for target.
appRadarDatabase_copy_qml/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_copy_qml.dir/build.make CMakeFiles/appRadarDatabase_copy_qml.dir/build
.PHONY : appRadarDatabase_copy_qml/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_copy_res

# Build rule for target.
appRadarDatabase_copy_res: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_copy_res
.PHONY : appRadarDatabase_copy_res

# fast build rule for target.
appRadarDatabase_copy_res/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_copy_res.dir/build.make CMakeFiles/appRadarDatabase_copy_res.dir/build
.PHONY : appRadarDatabase_copy_res/fast

#=============================================================================
# Target rules for targets named generate_qmlls_build_ini_file

# Build rule for target.
generate_qmlls_build_ini_file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_qmlls_build_ini_file
.PHONY : generate_qmlls_build_ini_file

# fast build rule for target.
generate_qmlls_build_ini_file/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate_qmlls_build_ini_file.dir/build.make CMakeFiles/generate_qmlls_build_ini_file.dir/build
.PHONY : generate_qmlls_build_ini_file/fast

#=============================================================================
# Target rules for targets named module_appRadarDatabase_aotstats_target

# Build rule for target.
module_appRadarDatabase_aotstats_target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 module_appRadarDatabase_aotstats_target
.PHONY : module_appRadarDatabase_aotstats_target

# fast build rule for target.
module_appRadarDatabase_aotstats_target/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/module_appRadarDatabase_aotstats_target.dir/build.make CMakeFiles/module_appRadarDatabase_aotstats_target.dir/build
.PHONY : module_appRadarDatabase_aotstats_target/fast

#=============================================================================
# Target rules for targets named all_aotstats

# Build rule for target.
all_aotstats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all_aotstats
.PHONY : all_aotstats

# fast build rule for target.
all_aotstats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/all_aotstats.dir/build.make CMakeFiles/all_aotstats.dir/build
.PHONY : all_aotstats/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_qmlimportscan

# Build rule for target.
appRadarDatabase_qmlimportscan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_qmlimportscan
.PHONY : appRadarDatabase_qmlimportscan

# fast build rule for target.
appRadarDatabase_qmlimportscan/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_qmlimportscan.dir/build.make CMakeFiles/appRadarDatabase_qmlimportscan.dir/build
.PHONY : appRadarDatabase_qmlimportscan/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_autogen_timestamp_deps

# Build rule for target.
appRadarDatabase_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_autogen_timestamp_deps
.PHONY : appRadarDatabase_autogen_timestamp_deps

# fast build rule for target.
appRadarDatabase_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_autogen_timestamp_deps.dir/build.make CMakeFiles/appRadarDatabase_autogen_timestamp_deps.dir/build
.PHONY : appRadarDatabase_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named appRadarDatabase_autogen

# Build rule for target.
appRadarDatabase_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 appRadarDatabase_autogen
.PHONY : appRadarDatabase_autogen

# fast build rule for target.
appRadarDatabase_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase_autogen.dir/build.make CMakeFiles/appRadarDatabase_autogen.dir/build
.PHONY : appRadarDatabase_autogen/fast

.qt/rcc/qrc_appRadarDatabase_raw_qml_0.o: .qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.o
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_qml_0.o

# target to build an object file
.qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.o
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.o

.qt/rcc/qrc_appRadarDatabase_raw_qml_0.i: .qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.i
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_qml_0.i

# target to preprocess a source file
.qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.i
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.i

.qt/rcc/qrc_appRadarDatabase_raw_qml_0.s: .qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.s
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_qml_0.s

# target to generate assembly for a file
.qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.s
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_qml_0.cpp.s

.qt/rcc/qrc_appRadarDatabase_raw_res_0.o: .qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.o
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_res_0.o

# target to build an object file
.qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.o
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.o

.qt/rcc/qrc_appRadarDatabase_raw_res_0.i: .qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.i
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_res_0.i

# target to preprocess a source file
.qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.i
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.i

.qt/rcc/qrc_appRadarDatabase_raw_res_0.s: .qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.s
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_res_0.s

# target to generate assembly for a file
.qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.s
.PHONY : .qt/rcc/qrc_appRadarDatabase_raw_res_0.cpp.s

.qt/rcc/qrc_qmake_RadarDatabase.o: .qt/rcc/qrc_qmake_RadarDatabase.cpp.o
.PHONY : .qt/rcc/qrc_qmake_RadarDatabase.o

# target to build an object file
.qt/rcc/qrc_qmake_RadarDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_qmake_RadarDatabase.cpp.o
.PHONY : .qt/rcc/qrc_qmake_RadarDatabase.cpp.o

.qt/rcc/qrc_qmake_RadarDatabase.i: .qt/rcc/qrc_qmake_RadarDatabase.cpp.i
.PHONY : .qt/rcc/qrc_qmake_RadarDatabase.i

# target to preprocess a source file
.qt/rcc/qrc_qmake_RadarDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_qmake_RadarDatabase.cpp.i
.PHONY : .qt/rcc/qrc_qmake_RadarDatabase.cpp.i

.qt/rcc/qrc_qmake_RadarDatabase.s: .qt/rcc/qrc_qmake_RadarDatabase.cpp.s
.PHONY : .qt/rcc/qrc_qmake_RadarDatabase.s

# target to generate assembly for a file
.qt/rcc/qrc_qmake_RadarDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.qt/rcc/qrc_qmake_RadarDatabase.cpp.s
.PHONY : .qt/rcc/qrc_qmake_RadarDatabase.cpp.s

.rcc/qmlcache/appRadarDatabase_Main_qml.o: .rcc/qmlcache/appRadarDatabase_Main_qml.cpp.o
.PHONY : .rcc/qmlcache/appRadarDatabase_Main_qml.o

# target to build an object file
.rcc/qmlcache/appRadarDatabase_Main_qml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.rcc/qmlcache/appRadarDatabase_Main_qml.cpp.o
.PHONY : .rcc/qmlcache/appRadarDatabase_Main_qml.cpp.o

.rcc/qmlcache/appRadarDatabase_Main_qml.i: .rcc/qmlcache/appRadarDatabase_Main_qml.cpp.i
.PHONY : .rcc/qmlcache/appRadarDatabase_Main_qml.i

# target to preprocess a source file
.rcc/qmlcache/appRadarDatabase_Main_qml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.rcc/qmlcache/appRadarDatabase_Main_qml.cpp.i
.PHONY : .rcc/qmlcache/appRadarDatabase_Main_qml.cpp.i

.rcc/qmlcache/appRadarDatabase_Main_qml.s: .rcc/qmlcache/appRadarDatabase_Main_qml.cpp.s
.PHONY : .rcc/qmlcache/appRadarDatabase_Main_qml.s

# target to generate assembly for a file
.rcc/qmlcache/appRadarDatabase_Main_qml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.rcc/qmlcache/appRadarDatabase_Main_qml.cpp.s
.PHONY : .rcc/qmlcache/appRadarDatabase_Main_qml.cpp.s

.rcc/qmlcache/appRadarDatabase_qmlcache_loader.o: .rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.o
.PHONY : .rcc/qmlcache/appRadarDatabase_qmlcache_loader.o

# target to build an object file
.rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.o
.PHONY : .rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.o

.rcc/qmlcache/appRadarDatabase_qmlcache_loader.i: .rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.i
.PHONY : .rcc/qmlcache/appRadarDatabase_qmlcache_loader.i

# target to preprocess a source file
.rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.i
.PHONY : .rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.i

.rcc/qmlcache/appRadarDatabase_qmlcache_loader.s: .rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.s
.PHONY : .rcc/qmlcache/appRadarDatabase_qmlcache_loader.s

# target to generate assembly for a file
.rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/.rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.s
.PHONY : .rcc/qmlcache/appRadarDatabase_qmlcache_loader.cpp.s

appRadarDatabase_autogen/mocs_compilation.o: appRadarDatabase_autogen/mocs_compilation.cpp.o
.PHONY : appRadarDatabase_autogen/mocs_compilation.o

# target to build an object file
appRadarDatabase_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/appRadarDatabase_autogen/mocs_compilation.cpp.o
.PHONY : appRadarDatabase_autogen/mocs_compilation.cpp.o

appRadarDatabase_autogen/mocs_compilation.i: appRadarDatabase_autogen/mocs_compilation.cpp.i
.PHONY : appRadarDatabase_autogen/mocs_compilation.i

# target to preprocess a source file
appRadarDatabase_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/appRadarDatabase_autogen/mocs_compilation.cpp.i
.PHONY : appRadarDatabase_autogen/mocs_compilation.cpp.i

appRadarDatabase_autogen/mocs_compilation.s: appRadarDatabase_autogen/mocs_compilation.cpp.s
.PHONY : appRadarDatabase_autogen/mocs_compilation.s

# target to generate assembly for a file
appRadarDatabase_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/appRadarDatabase_autogen/mocs_compilation.cpp.s
.PHONY : appRadarDatabase_autogen/mocs_compilation.cpp.s

appradardatabase_qmltyperegistrations.o: appradardatabase_qmltyperegistrations.cpp.o
.PHONY : appradardatabase_qmltyperegistrations.o

# target to build an object file
appradardatabase_qmltyperegistrations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/appradardatabase_qmltyperegistrations.cpp.o
.PHONY : appradardatabase_qmltyperegistrations.cpp.o

appradardatabase_qmltyperegistrations.i: appradardatabase_qmltyperegistrations.cpp.i
.PHONY : appradardatabase_qmltyperegistrations.i

# target to preprocess a source file
appradardatabase_qmltyperegistrations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/appradardatabase_qmltyperegistrations.cpp.i
.PHONY : appradardatabase_qmltyperegistrations.cpp.i

appradardatabase_qmltyperegistrations.s: appradardatabase_qmltyperegistrations.cpp.s
.PHONY : appradardatabase_qmltyperegistrations.s

# target to generate assembly for a file
appradardatabase_qmltyperegistrations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/appradardatabase_qmltyperegistrations.cpp.s
.PHONY : appradardatabase_qmltyperegistrations.cpp.s

database.o: database.cpp.o
.PHONY : database.o

# target to build an object file
database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/database.cpp.o
.PHONY : database.cpp.o

database.i: database.cpp.i
.PHONY : database.i

# target to preprocess a source file
database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/database.cpp.i
.PHONY : database.cpp.i

database.s: database.cpp.s
.PHONY : database.s

# target to generate assembly for a file
database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/database.cpp.s
.PHONY : database.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/main.cpp.s
.PHONY : main.cpp.s

navigation.o: navigation.cpp.o
.PHONY : navigation.o

# target to build an object file
navigation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/navigation.cpp.o
.PHONY : navigation.cpp.o

navigation.i: navigation.cpp.i
.PHONY : navigation.i

# target to preprocess a source file
navigation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/navigation.cpp.i
.PHONY : navigation.cpp.i

navigation.s: navigation.cpp.s
.PHONY : navigation.s

# target to generate assembly for a file
navigation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/navigation.cpp.s
.PHONY : navigation.cpp.s

shipmodel.o: shipmodel.cpp.o
.PHONY : shipmodel.o

# target to build an object file
shipmodel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/shipmodel.cpp.o
.PHONY : shipmodel.cpp.o

shipmodel.i: shipmodel.cpp.i
.PHONY : shipmodel.i

# target to preprocess a source file
shipmodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/shipmodel.cpp.i
.PHONY : shipmodel.cpp.i

shipmodel.s: shipmodel.cpp.s
.PHONY : shipmodel.s

# target to generate assembly for a file
shipmodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/shipmodel.cpp.s
.PHONY : shipmodel.cpp.s

worker.o: worker.cpp.o
.PHONY : worker.o

# target to build an object file
worker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/worker.cpp.o
.PHONY : worker.cpp.o

worker.i: worker.cpp.i
.PHONY : worker.i

# target to preprocess a source file
worker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/worker.cpp.i
.PHONY : worker.cpp.i

worker.s: worker.cpp.s
.PHONY : worker.s

# target to generate assembly for a file
worker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/appRadarDatabase.dir/build.make CMakeFiles/appRadarDatabase.dir/worker.cpp.s
.PHONY : worker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... all_aotstats"
	@echo "... all_qmllint"
	@echo "... all_qmllint_json"
	@echo "... all_qmllint_module"
	@echo "... all_qmltyperegistrations"
	@echo "... appRadarDatabase_autogen"
	@echo "... appRadarDatabase_autogen_timestamp_deps"
	@echo "... appRadarDatabase_copy_qml"
	@echo "... appRadarDatabase_copy_res"
	@echo "... appRadarDatabase_qmlimportscan"
	@echo "... appRadarDatabase_qmllint"
	@echo "... appRadarDatabase_qmllint_json"
	@echo "... appRadarDatabase_qmllint_module"
	@echo "... appRadarDatabase_qmltyperegistration"
	@echo "... clean_qml_context_properties"
	@echo "... dump_qml_context_properties"
	@echo "... generate_qmlls_build_ini_file"
	@echo "... module_appRadarDatabase_aotstats_target"
	@echo "... appRadarDatabase"
	@echo "... .qt/rcc/qrc_appRadarDatabase_raw_qml_0.o"
	@echo "... .qt/rcc/qrc_appRadarDatabase_raw_qml_0.i"
	@echo "... .qt/rcc/qrc_appRadarDatabase_raw_qml_0.s"
	@echo "... .qt/rcc/qrc_appRadarDatabase_raw_res_0.o"
	@echo "... .qt/rcc/qrc_appRadarDatabase_raw_res_0.i"
	@echo "... .qt/rcc/qrc_appRadarDatabase_raw_res_0.s"
	@echo "... .qt/rcc/qrc_qmake_RadarDatabase.o"
	@echo "... .qt/rcc/qrc_qmake_RadarDatabase.i"
	@echo "... .qt/rcc/qrc_qmake_RadarDatabase.s"
	@echo "... .rcc/qmlcache/appRadarDatabase_Main_qml.o"
	@echo "... .rcc/qmlcache/appRadarDatabase_Main_qml.i"
	@echo "... .rcc/qmlcache/appRadarDatabase_Main_qml.s"
	@echo "... .rcc/qmlcache/appRadarDatabase_qmlcache_loader.o"
	@echo "... .rcc/qmlcache/appRadarDatabase_qmlcache_loader.i"
	@echo "... .rcc/qmlcache/appRadarDatabase_qmlcache_loader.s"
	@echo "... appRadarDatabase_autogen/mocs_compilation.o"
	@echo "... appRadarDatabase_autogen/mocs_compilation.i"
	@echo "... appRadarDatabase_autogen/mocs_compilation.s"
	@echo "... appradardatabase_qmltyperegistrations.o"
	@echo "... appradardatabase_qmltyperegistrations.i"
	@echo "... appradardatabase_qmltyperegistrations.s"
	@echo "... database.o"
	@echo "... database.i"
	@echo "... database.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... navigation.o"
	@echo "... navigation.i"
	@echo "... navigation.s"
	@echo "... shipmodel.o"
	@echo "... shipmodel.i"
	@echo "... shipmodel.s"
	@echo "... worker.o"
	@echo "... worker.i"
	@echo "... worker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

